package by.vitikova.discovery.config;

import by.vitikova.discovery.UserDto;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.codec.ServerCodecConfigurer;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * Конфигурация шлюза (Gateway) для маршрутизации запросов.
 */
@Configuration
public class GatewayConfig implements WebMvcConfigurer {

    /**
     * Создает RouteLocator для конфигурации маршрутов шлюза.
     *
     * @param builder объект RouteLocatorBuilder для создания маршрутов
     * @return объект RouteLocator с настроенными маршрутами
     */
    @Bean
    public RouteLocator routeLocator(RouteLocatorBuilder builder) {
        return builder.routes()

                // image-service
                .route("pet-helper-image-service", r -> r.path("/api/v1/images")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/images/**")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/images")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/images/**")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/images")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/images/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))

                .route("pet-helper-image-service", r -> r.path("/api/v1/articlesImage")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/articlesImage/**")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/articlesImage")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/articlesImage/**")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/articlesImage")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/articlesImage/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))

                .route("pet-helper-image-service", r -> r.path("/api/v1/avatars")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/avatars/**")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/avatars")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/avatars/**")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/avatars")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/avatars/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))

                .route("pet-helper-image-service", r -> r.path("/api/v1/stateImages")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/stateImages/**")
                        .and().method("GET")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/stateImages")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/stateImages/**")
                        .and().method("POST")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/stateImages")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))
                .route("pet-helper-image-service", r -> r.path("/api/v1/stateImages/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8086"))

                // auth-service
                .route("pet-helper-auth-service", r -> r.path("/api/v1/auth/signUp")
                        .and().method("POST")
                        .uri("http://localhost:8082"))
                .route("pet-helper-auth-service", r -> r.path("/api/v1/auth/signIn")
                        .and().method("POST")
                        .uri("http://localhost:8082"))
                .route("pet-helper-auth-service", r -> r.path("/api/v1/auth/check")
                        .and().method("POST")
                        .uri("http://localhost:8082"))

                // user-service
                .route("pet-helper-user-service", r -> r.path("/api/v1/users/**")
                        .and().method("GET")
                        .uri("http://localhost:8081"))
                .route("pet-helper-user-service", r -> r.path("/api/v1/users/password/**")
                        .and().method("PUT")
                        .uri("http://localhost:8081"))

                // admin-service
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin")
                        .and().method("POST")
                        .and().readBody(UserDto.class, s -> true)
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin/**")
                        .and().method("POST")
                        .and().readBody(UserDto.class, s -> true)
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin")
                        .and().method("PUT")
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin")
                        .and().method("PATCH")
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin/**")
                        .and().method("GET")
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin")
                        .and().method("GET")
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8083"))
                .route("pet-helper-admin-service", r -> r.path("/api/v1/admin")
                        .and().method("DELETE")
                        .uri("http://localhost:8083"))

                // message-service
                .route("pet-helper-message-service", r -> r.path("/api/v1/chats")
                        .and().method("GET")
                        .uri("http://localhost:8084"))
                .route("pet-helper-message-service", r -> r.path("/api/v1/chats/**")
                        .and().method("GET")
                        .uri("http://localhost:8084"))
                .route("pet-helper-message-service", r -> r.path("/api/v1/chats")
                        .and().method("POST")
                        .uri("http://localhost:8084"))
                .route("pet-helper-message-service", r -> r.path("/api/v1/chats/**")
                        .and().method("POST")
                        .uri("http://localhost:8084"))
                .route("pet-helper-message-service", r -> r.path("/api/v1/chats/**")
                        .and().method("PUT")
                        .uri("http://localhost:8084"))
                .route("pet-helper-message-service", r -> r.path("/api/v1/chats/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8084"))

                // pet-helper-editor-service
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates/**")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates/**")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates/**")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/stateTemplates/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8087"))

                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes/**")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes/**")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes/**")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/animalTypes/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8087"))

                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes/**")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes/**")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes/**")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/vaccinationTypes/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8087"))

                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds/**")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds/**")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds/**")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/breeds/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8087"))

                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags/**")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags/**")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags/**")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/tags/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8087"))

                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles/**")
                        .and().method("GET")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles/**")
                        .and().method("POST")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles/**")
                        .and().method("PUT")
                        .uri("http://localhost:8087"))
                .route("pet-helper-editor-service", r -> r.path("/api/v1/articles/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8087"))

                // pet-helper-service
                .route("pet-helper-service", r -> r.path("/api/v1/records")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/records/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/records")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/records/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/records/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/records/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/pedigree")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/pedigree/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/pedigree")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/pedigree/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/pedigree")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/pedigree/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/pedigree/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/parents")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/parents/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/parents")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/parents/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/parents/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/states")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/states/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/states")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/states/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/states")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/states/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/states/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/dictionaries/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/eventDictionaries/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/events")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/events/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/events")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/events/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/events")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/events/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/events/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notificationTimes/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/notifications")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notifications/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notifications")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notifications/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notifications")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notifications/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/notifications/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles/**")
                        .and().method("POST")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles/**")
                        .and().method("PUT")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/favoriteArticles/**")
                        .and().method("DELETE")
                        .uri("http://localhost:8085"))

                .route("pet-helper-service", r -> r.path("/api/v1/recommender")
                        .and().method("GET")
                        .uri("http://localhost:8085"))
                .route("pet-helper-service", r -> r.path("/api/v1/recommender/**")
                        .and().method("GET")
                        .uri("http://localhost:8085"))

                .build();
    }

    /**
     * Создает ServerCodecConfigurer для настройки кодеков.
     *
     * @return объект ServerCodecConfigurer
     */
    @Bean
    public ServerCodecConfigurer serverCodecConfigurer() {
        return ServerCodecConfigurer.create();
    }
}